FROM docker.io/golang:1.21 as build

WORKDIR cmd/server
COPY . .

RUN ls
RUN CGO_ENABLED=0 go build -o /go/bin/petra ./cmd/server

FROM gcr.io/distroless/static-debian11
COPY --from=build /go/bin/petra /
CMD ["/petra"]