before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
release:
  prerelease: auto
dockers:
  -
    image_templates:
    - "docker.pkg.github.com/devoteamgcloud/petra/{{ .ProjectName }}:latest"
    - "docker.pkg.github.com/devoteamgcloud/petra/{{ .ProjectName }}:{{ .Major }}"
    - "docker.pkg.github.com/devoteamgcloud/petra/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/devoteamgcloud/petra/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
